
import { Contact, AppLanguage, Tool } from './types';

export const INITIAL_CONTACTS: Contact[] = [];

export const INITIAL_TOOLS: Tool[] = [];

export const SUPPORTED_LANGUAGES: { code: AppLanguage; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
];

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    title: "The Planning Room",
    dashboard: "Dashboard",
    planning: "Whiteboard",
    document: "Strategic Doc",
    scan: "Scan / Write",
    strategicPlan: "Strategic Plan",
    backToBoard: "Back to Board",
    strategicGoals: "Strategic Goals",
    missionObjectives: "Mission Objectives",
    actionItems: "Action Items",
    conceptRepository: "Concept Repository",
    noGoals: "No strategic goals defined.",
    noObjectives: "No objectives set.",
    noTasks: "No action items created.",
    requires: "Requires",
    inputs: "inputs",
    contributes: "Contributes to",
    outcomes: "outcomes",
    scannerTitle: "Document Processor",
    scannerSubtitle: "Write or paste content below. Right-click blocks to tag them for the whiteboard.",
    addTextBlock: "Add Text",
    addImageBlock: "Add Image",
    syncToBoard: "Sync to Board",
    tagAsGoal: "Tag as Goal",
    tagAsObjective: "Tag as Objective",
    tagAsTask: "Tag as Task",
    tagAsIdea: "Tag as Idea",
    tagAsImage: "Tag as Board Image",
    untag: "Remove Tag",
    welcome: "Welcome back",
    projectOverview: "Project Overview",
    quickAccess: "Quick Access",
    openBoard: "Open Board",
    openDocument: "View Document",
    startScan: "New Scan",
    totalGoals: "Total Goals",
    activeObjectives: "Active Objectives",
    pendingTasks: "Pending Tasks",
    latestProject: "Latest Project",
    lastEdited: "Last edited just now",
    items: "items",
    profilePicture: "Profile Picture",
    givenName: "Given Name",
    surname: "Surname",
    emailAddress: "Email Address",
    phone: "Phone",
    company: "Company",
    position: "Position",
    customLists: "Custom Lists",
    registryDate: "Registry Date",
    remarks: "Remarks",
    discard: "Discard",
    updateProfile: "Update Profile",
    confirmRegistry: "Confirm Registry",
    personnel: "Personnel",
    privatePractice: "Private Practice",
    joined: "Joined",
    dbRegistry: "DB Registry",
    modify: "Modify",
    erase: "Erase",
    createRoom: "Create Planning Room",
    roomName: "Room Name",
    roomDescription: "Mission Description",
    roomTheme: "Theme Color",
    yourRooms: "Your Planning Rooms",
    noRooms: "No active planning rooms. Start your first mission below.",
    newMission: "New Mission",
    deleteRoom: "Delete Room"
  }
};
