
import { Contact, AppLanguage, Tool } from './types';

export const INITIAL_CONTACTS: Contact[] = [];

export const INITIAL_TOOLS: Tool[] = [];

export const SUPPORTED_LANGUAGES: { code: AppLanguage; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: 'Mandarin', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
];

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    title: "The Planning Room",
    planning: "Whiteboard",
    document: "Strategic Doc",
    scan: "Scan / Write",
    strategicPlan: "Strategic Plan",
    backToBoard: "Back to Board",
    strategicGoals: "Strategic Goals",
    missionObjectives: "Mission Objectives",
    actionItems: "Action Items",
    conceptRepository: "Concept Repository",
    noGoals: "No strategic goals defined.",
    noObjectives: "No objectives set.",
    noTasks: "No action items created.",
    requires: "Requires",
    inputs: "inputs",
    contributes: "Contributes to",
    outcomes: "outcomes",
    scannerTitle: "Document Processor",
    scannerSubtitle: "Write or paste content below. Right-click blocks to tag them for the whiteboard.",
    addTextBlock: "Add Text",
    addImageBlock: "Add Image",
    syncToBoard: "Sync to Board",
    tagAsGoal: "Tag as Goal",
    tagAsObjective: "Tag as Objective",
    tagAsTask: "Tag as Task",
    tagAsIdea: "Tag as Idea",
    tagAsImage: "Tag as Board Image",
    untag: "Remove Tag"
  },
  fr: {
    title: "La Salle de Planification",
    planning: "Tableau Blanc",
    document: "Doc Stratégique",
    scan: "Scanner / Écrire",
    strategicPlan: "Plan Stratégique",
    backToBoard: "Retour au tableau",
    strategicGoals: "Objectifs Stratégiques",
    missionObjectives: "Objectifs de Mission",
    actionItems: "Actions",
    conceptRepository: "Répertoire de Concepts",
    noGoals: "Aucun objectif stratégique défini.",
    noObjectives: "Aucun objectif défini.",
    noTasks: "Aucune action créée.",
    requires: "Nécessite",
    inputs: "entrées",
    contributes: "Contribue à",
    outcomes: "résultats",
    scannerTitle: "Processeur de Documents",
    scannerSubtitle: "Écrivez ou collez du contenu. Clic droit pour taguer.",
    addTextBlock: "Ajouter Texte",
    addImageBlock: "Ajouter Image",
    syncToBoard: "Synchro Tableau",
    tagAsGoal: "Tagger comme But",
    tagAsObjective: "Tagger comme Objectif",
    tagAsTask: "Tagger comme Tâche",
    tagAsIdea: "Tagger comme Idée",
    tagAsImage: "Tagger comme Image",
    untag: "Enlever le tag"
  },
  de: {
    title: "Der Planungsraum",
    planning: "Whiteboard",
    document: "Strategiepapier",
    scan: "Scannen / Schreiben",
    strategicPlan: "Strategischer Plan",
    backToBoard: "Zurück zum Board",
    strategicGoals: "Strategische Ziele",
    missionObjectives: "Missionsziele",
    actionItems: "Aktionspunkte",
    conceptRepository: "Konzeptspeicher",
    noGoals: "Keine strategischen Ziele definiert.",
    noObjectives: "Keine Ziele gesetzt.",
    noTasks: "Keine Aktionspunkte erstellt.",
    requires: "Benötigt",
    inputs: "Eingaben",
    contributes: "Trägt bei zu",
    outcomes: "Ergebnissen",
    scannerTitle: "Dokumentenprozessor",
    scannerSubtitle: "Inhalt schreiben oder einfügen. Rechtsklick zum Taggen.",
    addTextBlock: "Text hinzufügen",
    addImageBlock: "Bild hinzufügen",
    syncToBoard: "Mit Board synchronisieren",
    tagAsGoal: "Als Ziel taggen",
    tagAsObjective: "Als Objektiv taggen",
    tagAsTask: "Als Aufgabe taggen",
    tagAsIdea: "Als Idee taggen",
    tagAsImage: "Als Bild taggen",
    untag: "Tag entfernen"
  },
  ru: {
    title: "Комната планирования",
    planning: "Доска",
    document: "Стратегия",
    scan: "Скан / Письмо",
    strategicPlan: "Стратегический план",
    backToBoard: "Назад к доске",
    strategicGoals: "Стратегические цели",
    missionObjectives: "Цели миссии",
    actionItems: "Задачи",
    conceptRepository: "Репозиторий концепций",
    noGoals: "Стратегические цели не определены.",
    noObjectives: "Цели не заданы.",
    noTasks: "Задачи не созданы.",
    requires: "Требует",
    inputs: "входов",
    contributes: "Способствует",
    outcomes: "результатам",
    scannerTitle: "Обработка документов",
    scannerSubtitle: "Напишите или вставьте контент. ПКМ для тегирования.",
    addTextBlock: "Добавить текст",
    addImageBlock: "Добавить изображение",
    syncToBoard: "Синхронизация",
    tagAsGoal: "Как цель",
    tagAsObjective: "Как задачу миссии",
    tagAsTask: "Как задачу",
    tagAsIdea: "Как идею",
    tagAsImage: "Как изображение",
    untag: "Снять тег"
  },
  ar: {
    title: "غرفة التخطيط",
    planning: "السبورة البيضاء",
    document: "وثيقة الاستراتيجية",
    scan: "مسح / كتابة",
    strategicPlan: "الخطة الاستراتيجية",
    backToBoard: "عودة للوحة",
    strategicGoals: "الأهداف الاستراتيجية",
    missionObjectives: "أهداف المهمة",
    actionItems: "عناصر العمل",
    conceptRepository: "مستودع المفاهيم",
    noGoals: "لم يتم تحديد أهداف استراتيجية.",
    noObjectives: "لم يتم تحديد أهداف.",
    noTasks: "لم يتم إنشاء عناصر عمل.",
    requires: "يتطلب",
    inputs: "مدخلات",
    contributes: "يساهم في",
    outcomes: "نتائج",
    scannerTitle: "معالج الوثائق",
    scannerSubtitle: "اكتب أو الصق المحتوى. انقر بزر الماوس الأيمن لوضع علامة.",
    addTextBlock: "إضافة نص",
    addImageBlock: "إضافة صورة",
    syncToBoard: "مزامنة مع اللوحة",
    tagAsGoal: "وسم كهدف",
    tagAsObjective: "وسم كمهمة",
    tagAsTask: "وسم كمهمة عمل",
    tagAsIdea: "وسم كفكرة",
    tagAsImage: "وسم كصورة",
    untag: "إزالة الوسم"
  },
  zh: {
    title: "规划室",
    planning: "白板",
    document: "战略文档",
    scan: "扫描 / 写作",
    strategicPlan: "战略计划",
    backToBoard: "返回看板",
    strategicGoals: "战略目标",
    missionObjectives: "任务目标",
    actionItems: "行动项",
    conceptRepository: "概念库",
    noGoals: "未定义战略目标。",
    noObjectives: "未设定目标。",
    noTasks: "未创建行动项。",
    requires: "需要",
    inputs: "输入",
    contributes: "贡献于",
    outcomes: "结果",
    scannerTitle: "文档处理器",
    scannerSubtitle: "编写或粘贴内容。右键点击块进行标记。",
    addTextBlock: "添加文本",
    addImageBlock: "添加图片",
    syncToBoard: "同步到看板",
    tagAsGoal: "标记为目标",
    tagAsObjective: "标记为任务目标",
    tagAsTask: "标记为任务",
    tagAsIdea: "标记为想法",
    tagAsImage: "标记为图片",
    untag: "移除标记"
  },
  ja: {
    title: "プランニングルーム",
    planning: "ホワイトボード",
    document: "戦略文書",
    scan: "スキャン / 作成",
    strategicPlan: "戦略計画",
    backToBoard: "ボードに戻る",
    strategicGoals: "戦略目標",
    missionObjectives: "ミッション目標",
    actionItems: "アクションアイテム",
    conceptRepository: "コンセプト",
    noGoals: "戦略目標が定義されていません。",
    noObjectives: "目標が設定されていません。",
    noTasks: "アクションアイテムが作成されていません。",
    requires: "必要",
    inputs: "入力",
    contributes: "貢献",
    outcomes: "結果",
    scannerTitle: "ドキュメントプロセッサ",
    scannerSubtitle: "コンテンツを作成または貼り付けます。右クリックでタグ付けします。",
    addTextBlock: "テキストを追加",
    addImageBlock: "画像を追加",
    syncToBoard: "ボードに同期",
    tagAsGoal: "目標としてタグ付け",
    tagAsObjective: "目的としてタグ付け",
    tagAsTask: "タスクとしてタグ付け",
    tagAsIdea: "アイデアとしてタグ付け",
    tagAsImage: "画像としてタグ付け",
    untag: "タグを削除"
  },
  ko: {
    title: "기획실",
    planning: "화이트보드",
    document: "전략 문서",
    scan: "스캔 / 작성",
    strategicPlan: "전략 계획",
    backToBoard: "보드로 돌아가기",
    strategicGoals: "전략적 목표",
    missionObjectives: "미션 목표",
    actionItems: "액션 아이템",
    conceptRepository: "컨셉 저장소",
    noGoals: "정의된 전략적 목표가 없습니다.",
    noObjectives: "설정된 목표가 없습니다.",
    noTasks: "생성된 액션 아이템이 없습니다.",
    requires: "필요",
    inputs: "입력",
    contributes: "기여",
    outcomes: "결과",
    scannerTitle: "문서 프로세서",
    scannerSubtitle: "내용을 작성하거나 붙여넣으세요. 마우스 오른쪽 버튼을 클릭하여 태그를 지정하세요.",
    addTextBlock: "텍스트 추가",
    addImageBlock: "이미지 추가",
    syncToBoard: "보드와 동기화",
    tagAsGoal: "목표로 태그",
    tagAsObjective: "미션으로 태그",
    tagAsTask: "작업으로 태그",
    tagAsIdea: "아이디어로 태그",
    tagAsImage: "이미지로 태그",
    untag: "태그 제거"
  }
};
